version: '2.1'
services:

  support2.0-management-center:
    image: registry.fit2cloud.com/innovation/support2.0-management-center:master
    container_name: support2.0-management-center
    ports:
      - 6602:6602
    volumes:
      - host-opt-fit2cloud-conf:/opt/fit2cloud/conf
      - host-opt-fit2cloud-logs:/opt/fit2cloud/logs
    mem_limit: 1024m
    networks:
      - support-network

  support2.0-gateway:
    image: registry.fit2cloud.com/innovation/support2.0-gateway:master
    container_name: support2.0-gateway
    ports:
      - 8088:6601
    volumes:
      - host-opt-fit2cloud-conf:/opt/fit2cloud/conf
      - host-opt-fit2cloud-logs:/opt/fit2cloud/logs
    mem_limit: 1024m
    networks:
      - support-network

  keycloak:
    image: registry.fit2cloud.com/innovation/keycloak:4.8.3.Final
    container_name: keycloak
    env_file:
      - ./conf/keycloak.properties
    ports:
      - 8881:8080
    command:
      - -b 0.0.0.0 -Dkeycloak.import=/opt/fit2cloud/conf/cmp-realm.json
    volumes:
      - host-opt-fit2cloud-conf:/opt/fit2cloud/conf
      - host-opt-fit2cloud-logs:/opt/fit2cloud/logs
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - support-network

  redis:
    image: registry.fit2cloud.com/fit2cloud2/redis:5.0.3-alpine
    container_name: redis
    command: ["/etc/redis.conf"]
    ports:
      - 6379:6379
    volumes:
      - /opt/fit2cloud/conf/redis.conf:/etc/redis.conf
      - host-opt-fit2cloud-redis-data:/data
    networks:
      - support-network

  mysql:
    image: registry.fit2cloud.com/fit2cloud2/mysql:5.7.24
    container_name: mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
    env_file:
      - /opt/fit2cloud/conf/mysql.env
    ports:
      - 3306:3306
    volumes:
      - /opt/fit2cloud/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - /opt/fit2cloud/bin/mysql:/docker-entrypoint-initdb.d/
      - host-opt-fit2cloud-mysql-data:/var/lib/mysql
    networks:
      - support-network

volumes:
  host-opt-fit2cloud-conf:
    driver_opts:
      type: none
      device: /opt/fit2cloud/conf
      o: bind
  host-opt-fit2cloud-logs:
    driver_opts:
      type: none
      device: /opt/fit2cloud/logs
      o: bind
  host-opt-fit2cloud-mysql-data:
    driver_opts:
      type: none
      device: /opt/fit2cloud/data/mysql
      o: bind

networks:
  support-network:
