package com.fit2cloud.support.model;

public class AgentCompany {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_company.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_company.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_company.agent_id
     *
     * @mbg.generated
     */
    private String agentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_company.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_company.id
     *
     * @return the value of agent_company.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_company.id
     *
     * @param id the value for agent_company.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_company.company_id
     *
     * @return the value of agent_company.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_company.company_id
     *
     * @param companyId the value for agent_company.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_company.agent_id
     *
     * @return the value of agent_company.agent_id
     *
     * @mbg.generated
     */
    public String getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_company.agent_id
     *
     * @param agentId the value for agent_company.agent_id
     *
     * @mbg.generated
     */
    public void setAgentId(String agentId) {
        this.agentId = agentId == null ? null : agentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_company.create_time
     *
     * @return the value of agent_company.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_company.create_time
     *
     * @param createTime the value for agent_company.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
}