package com.fit2cloud.support.model;

public class AgentSubscription {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_subscription.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_subscription.agent_id
     *
     * @mbg.generated
     */
    private String agentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_subscription.subscription_id
     *
     * @mbg.generated
     */
    private String subscriptionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent_subscription.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_subscription.id
     *
     * @return the value of agent_subscription.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_subscription.id
     *
     * @param id the value for agent_subscription.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_subscription.agent_id
     *
     * @return the value of agent_subscription.agent_id
     *
     * @mbg.generated
     */
    public String getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_subscription.agent_id
     *
     * @param agentId the value for agent_subscription.agent_id
     *
     * @mbg.generated
     */
    public void setAgentId(String agentId) {
        this.agentId = agentId == null ? null : agentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_subscription.subscription_id
     *
     * @return the value of agent_subscription.subscription_id
     *
     * @mbg.generated
     */
    public String getSubscriptionId() {
        return subscriptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_subscription.subscription_id
     *
     * @param subscriptionId the value for agent_subscription.subscription_id
     *
     * @mbg.generated
     */
    public void setSubscriptionId(String subscriptionId) {
        this.subscriptionId = subscriptionId == null ? null : subscriptionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent_subscription.create_time
     *
     * @return the value of agent_subscription.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent_subscription.create_time
     *
     * @param createTime the value for agent_subscription.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
}