package com.fit2cloud.support.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

public class Agent implements Serializable {
    @ApiModelProperty("")
    private String id;

    @ApiModelProperty("代理商名称")
    private String name;

    @ApiModelProperty("代理商邮箱")
    private String email;

    @ApiModelProperty("代理商电话")
    private String phone;

    @ApiModelProperty("")
    private Boolean isDelete;

    @ApiModelProperty("创建时间")
    private Long createTime;

    @ApiModelProperty("代理商简介")
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table agent
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.id
     *
     * @return the value of agent.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.id
     *
     * @param id the value for agent.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.name
     *
     * @return the value of agent.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.name
     *
     * @param name the value for agent.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.email
     *
     * @return the value of agent.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.email
     *
     * @param email the value for agent.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.phone
     *
     * @return the value of agent.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.phone
     *
     * @param phone the value for agent.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.is_delete
     *
     * @return the value of agent.is_delete
     *
     * @mbg.generated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.is_delete
     *
     * @param isDelete the value for agent.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.create_time
     *
     * @return the value of agent.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.create_time
     *
     * @param createTime the value for agent.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.description
     *
     * @return the value of agent.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.description
     *
     * @param description the value for agent.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}