package com.fit2cloud.support.model;

import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;

public class ExtraUserLog implements Serializable {
    @ApiModelProperty("")
    private String id;

    @ApiModelProperty("")
    private String name;

    @ApiModelProperty("")
    private String email;

    @ApiModelProperty("")
    private String userName;

    @ApiModelProperty("")
    private Long createTime;

    @ApiModelProperty("")
    private String status;

    @ApiModelProperty("")
    private String groupEnvId;

    @ApiModelProperty("")
    private String groupEnvName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table extra_user_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column extra_user_log.id
     *
     * @return the value of extra_user_log.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column extra_user_log.id
     *
     * @param id the value for extra_user_log.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column extra_user_log.name
     *
     * @return the value of extra_user_log.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column extra_user_log.name
     *
     * @param name the value for extra_user_log.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column extra_user_log.email
     *
     * @return the value of extra_user_log.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column extra_user_log.email
     *
     * @param email the value for extra_user_log.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column extra_user_log.user_name
     *
     * @return the value of extra_user_log.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column extra_user_log.user_name
     *
     * @param userName the value for extra_user_log.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column extra_user_log.create_time
     *
     * @return the value of extra_user_log.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column extra_user_log.create_time
     *
     * @param createTime the value for extra_user_log.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column extra_user_log.status
     *
     * @return the value of extra_user_log.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column extra_user_log.status
     *
     * @param status the value for extra_user_log.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column extra_user_log.group_env_id
     *
     * @return the value of extra_user_log.group_env_id
     *
     * @mbg.generated
     */
    public String getGroupEnvId() {
        return groupEnvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column extra_user_log.group_env_id
     *
     * @param groupEnvId the value for extra_user_log.group_env_id
     *
     * @mbg.generated
     */
    public void setGroupEnvId(String groupEnvId) {
        this.groupEnvId = groupEnvId == null ? null : groupEnvId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column extra_user_log.group_env_name
     *
     * @return the value of extra_user_log.group_env_name
     *
     * @mbg.generated
     */
    public String getGroupEnvName() {
        return groupEnvName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column extra_user_log.group_env_name
     *
     * @param groupEnvName the value for extra_user_log.group_env_name
     *
     * @mbg.generated
     */
    public void setGroupEnvName(String groupEnvName) {
        this.groupEnvName = groupEnvName == null ? null : groupEnvName.trim();
    }
}
