package com.fit2cloud.support.model;

import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;

public class ExtraDataLog implements Serializable {
    @ApiModelProperty("")
    private String id;

    @ApiModelProperty("")
    private Long createTime;

    @ApiModelProperty("数据日志")
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table extra_data_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column extra_data_log.id
     *
     * @return the value of extra_data_log.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column extra_data_log.id
     *
     * @param id the value for extra_data_log.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column extra_data_log.create_time
     *
     * @return the value of extra_data_log.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column extra_data_log.create_time
     *
     * @param createTime the value for extra_data_log.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column extra_data_log.description
     *
     * @return the value of extra_data_log.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column extra_data_log.description
     *
     * @param description the value for extra_data_log.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}
