package com.fit2cloud.support.model;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.icon_url
     *
     * @mbg.generated
     */
    private String iconUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.is_delete
     *
     * @mbg.generated
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.relation_sku_id
     *
     * @mbg.generated
     */
    private String relationSkuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.front_end_url
     *
     * @mbg.generated
     */
    private String frontEndUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.admin_url
     *
     * @mbg.generated
     */
    private String adminUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.auth_url
     *
     * @mbg.generated
     */
    private String authUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.habor_project_id
     *
     * @mbg.generated
     */
    private Long haborProjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.expiration_time
     *
     * @mbg.generated
     */
    private Long expirationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.authorization_count
     *
     * @mbg.generated
     */
    private Integer authorizationCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_classification
     *
     * @mbg.generated
     */
    private String productClassification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_edition
     *
     * @mbg.generated
     */
    private String productEdition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sku_id
     *
     * @mbg.generated
     */
    private String skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.grade_service_id
     *
     * @mbg.generated
     */
    private String gradeServiceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_version_summary_id
     *
     * @mbg.generated
     */
    private String productVersionSummaryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.name
     *
     * @return the value of product.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.name
     *
     * @param name the value for product.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.icon_url
     *
     * @return the value of product.icon_url
     *
     * @mbg.generated
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.icon_url
     *
     * @param iconUrl the value for product.icon_url
     *
     * @mbg.generated
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl == null ? null : iconUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.create_time
     *
     * @return the value of product.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.create_time
     *
     * @param createTime the value for product.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.is_delete
     *
     * @return the value of product.is_delete
     *
     * @mbg.generated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.is_delete
     *
     * @param isDelete the value for product.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.relation_sku_id
     *
     * @return the value of product.relation_sku_id
     *
     * @mbg.generated
     */
    public String getRelationSkuId() {
        return relationSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.relation_sku_id
     *
     * @param relationSkuId the value for product.relation_sku_id
     *
     * @mbg.generated
     */
    public void setRelationSkuId(String relationSkuId) {
        this.relationSkuId = relationSkuId == null ? null : relationSkuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.front_end_url
     *
     * @return the value of product.front_end_url
     *
     * @mbg.generated
     */
    public String getFrontEndUrl() {
        return frontEndUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.front_end_url
     *
     * @param frontEndUrl the value for product.front_end_url
     *
     * @mbg.generated
     */
    public void setFrontEndUrl(String frontEndUrl) {
        this.frontEndUrl = frontEndUrl == null ? null : frontEndUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.admin_url
     *
     * @return the value of product.admin_url
     *
     * @mbg.generated
     */
    public String getAdminUrl() {
        return adminUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.admin_url
     *
     * @param adminUrl the value for product.admin_url
     *
     * @mbg.generated
     */
    public void setAdminUrl(String adminUrl) {
        this.adminUrl = adminUrl == null ? null : adminUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.auth_url
     *
     * @return the value of product.auth_url
     *
     * @mbg.generated
     */
    public String getAuthUrl() {
        return authUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.auth_url
     *
     * @param authUrl the value for product.auth_url
     *
     * @mbg.generated
     */
    public void setAuthUrl(String authUrl) {
        this.authUrl = authUrl == null ? null : authUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.habor_project_id
     *
     * @return the value of product.habor_project_id
     *
     * @mbg.generated
     */
    public Long getHaborProjectId() {
        return haborProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.habor_project_id
     *
     * @param haborProjectId the value for product.habor_project_id
     *
     * @mbg.generated
     */
    public void setHaborProjectId(Long haborProjectId) {
        this.haborProjectId = haborProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.expiration_time
     *
     * @return the value of product.expiration_time
     *
     * @mbg.generated
     */
    public Long getExpirationTime() {
        return expirationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.expiration_time
     *
     * @param expirationTime the value for product.expiration_time
     *
     * @mbg.generated
     */
    public void setExpirationTime(Long expirationTime) {
        this.expirationTime = expirationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.authorization_count
     *
     * @return the value of product.authorization_count
     *
     * @mbg.generated
     */
    public Integer getAuthorizationCount() {
        return authorizationCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.authorization_count
     *
     * @param authorizationCount the value for product.authorization_count
     *
     * @mbg.generated
     */
    public void setAuthorizationCount(Integer authorizationCount) {
        this.authorizationCount = authorizationCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_classification
     *
     * @return the value of product.product_classification
     *
     * @mbg.generated
     */
    public String getProductClassification() {
        return productClassification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_classification
     *
     * @param productClassification the value for product.product_classification
     *
     * @mbg.generated
     */
    public void setProductClassification(String productClassification) {
        this.productClassification = productClassification == null ? null : productClassification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_edition
     *
     * @return the value of product.product_edition
     *
     * @mbg.generated
     */
    public String getProductEdition() {
        return productEdition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_edition
     *
     * @param productEdition the value for product.product_edition
     *
     * @mbg.generated
     */
    public void setProductEdition(String productEdition) {
        this.productEdition = productEdition == null ? null : productEdition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sku_id
     *
     * @return the value of product.sku_id
     *
     * @mbg.generated
     */
    public String getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sku_id
     *
     * @param skuId the value for product.sku_id
     *
     * @mbg.generated
     */
    public void setSkuId(String skuId) {
        this.skuId = skuId == null ? null : skuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.grade_service_id
     *
     * @return the value of product.grade_service_id
     *
     * @mbg.generated
     */
    public String getGradeServiceId() {
        return gradeServiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.grade_service_id
     *
     * @param gradeServiceId the value for product.grade_service_id
     *
     * @mbg.generated
     */
    public void setGradeServiceId(String gradeServiceId) {
        this.gradeServiceId = gradeServiceId == null ? null : gradeServiceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_version_summary_id
     *
     * @return the value of product.product_version_summary_id
     *
     * @mbg.generated
     */
    public String getProductVersionSummaryId() {
        return productVersionSummaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_version_summary_id
     *
     * @param productVersionSummaryId the value for product.product_version_summary_id
     *
     * @mbg.generated
     */
    public void setProductVersionSummaryId(String productVersionSummaryId) {
        this.productVersionSummaryId = productVersionSummaryId == null ? null : productVersionSummaryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.content
     *
     * @return the value of product.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.content
     *
     * @param content the value for product.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}