package com.fit2cloud.support.model;

public class Subscription {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.uid
     *
     * @mbg.generated
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.order_biz_id
     *
     * @mbg.generated
     */
    private String orderBizId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.expiration_time
     *
     * @mbg.generated
     */
    private Long expirationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.sale_id
     *
     * @mbg.generated
     */
    private String saleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.product_id
     *
     * @mbg.generated
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.support_user_id
     *
     * @mbg.generated
     */
    private String supportUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.instance_id
     *
     * @mbg.generated
     */
    private String instanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.is_delete
     *
     * @mbg.generated
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.authorization_count
     *
     * @mbg.generated
     */
    private Integer authorizationCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.subscription_license_id
     *
     * @mbg.generated
     */
    private String subscriptionLicenseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscription.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.id
     *
     * @return the value of subscription.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.id
     *
     * @param id the value for subscription.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.uid
     *
     * @return the value of subscription.uid
     *
     * @mbg.generated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.uid
     *
     * @param uid the value for subscription.uid
     *
     * @mbg.generated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.order_biz_id
     *
     * @return the value of subscription.order_biz_id
     *
     * @mbg.generated
     */
    public String getOrderBizId() {
        return orderBizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.order_biz_id
     *
     * @param orderBizId the value for subscription.order_biz_id
     *
     * @mbg.generated
     */
    public void setOrderBizId(String orderBizId) {
        this.orderBizId = orderBizId == null ? null : orderBizId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.order_id
     *
     * @return the value of subscription.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.order_id
     *
     * @param orderId the value for subscription.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.expiration_time
     *
     * @return the value of subscription.expiration_time
     *
     * @mbg.generated
     */
    public Long getExpirationTime() {
        return expirationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.expiration_time
     *
     * @param expirationTime the value for subscription.expiration_time
     *
     * @mbg.generated
     */
    public void setExpirationTime(Long expirationTime) {
        this.expirationTime = expirationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.create_time
     *
     * @return the value of subscription.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.create_time
     *
     * @param createTime the value for subscription.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.sale_id
     *
     * @return the value of subscription.sale_id
     *
     * @mbg.generated
     */
    public String getSaleId() {
        return saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.sale_id
     *
     * @param saleId the value for subscription.sale_id
     *
     * @mbg.generated
     */
    public void setSaleId(String saleId) {
        this.saleId = saleId == null ? null : saleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.company_id
     *
     * @return the value of subscription.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.company_id
     *
     * @param companyId the value for subscription.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.email
     *
     * @return the value of subscription.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.email
     *
     * @param email the value for subscription.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.product_id
     *
     * @return the value of subscription.product_id
     *
     * @mbg.generated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.product_id
     *
     * @param productId the value for subscription.product_id
     *
     * @mbg.generated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.support_user_id
     *
     * @return the value of subscription.support_user_id
     *
     * @mbg.generated
     */
    public String getSupportUserId() {
        return supportUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.support_user_id
     *
     * @param supportUserId the value for subscription.support_user_id
     *
     * @mbg.generated
     */
    public void setSupportUserId(String supportUserId) {
        this.supportUserId = supportUserId == null ? null : supportUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.instance_id
     *
     * @return the value of subscription.instance_id
     *
     * @mbg.generated
     */
    public String getInstanceId() {
        return instanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.instance_id
     *
     * @param instanceId the value for subscription.instance_id
     *
     * @mbg.generated
     */
    public void setInstanceId(String instanceId) {
        this.instanceId = instanceId == null ? null : instanceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.is_delete
     *
     * @return the value of subscription.is_delete
     *
     * @mbg.generated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.is_delete
     *
     * @param isDelete the value for subscription.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.authorization_count
     *
     * @return the value of subscription.authorization_count
     *
     * @mbg.generated
     */
    public Integer getAuthorizationCount() {
        return authorizationCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.authorization_count
     *
     * @param authorizationCount the value for subscription.authorization_count
     *
     * @mbg.generated
     */
    public void setAuthorizationCount(Integer authorizationCount) {
        this.authorizationCount = authorizationCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.subscription_license_id
     *
     * @return the value of subscription.subscription_license_id
     *
     * @mbg.generated
     */
    public String getSubscriptionLicenseId() {
        return subscriptionLicenseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.subscription_license_id
     *
     * @param subscriptionLicenseId the value for subscription.subscription_license_id
     *
     * @mbg.generated
     */
    public void setSubscriptionLicenseId(String subscriptionLicenseId) {
        this.subscriptionLicenseId = subscriptionLicenseId == null ? null : subscriptionLicenseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscription.remarks
     *
     * @return the value of subscription.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscription.remarks
     *
     * @param remarks the value for subscription.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}