package com.fit2cloud.support.dao;

import com.fit2cloud.support.model.AliyunMarketRecord;
import com.fit2cloud.support.model.AliyunMarketRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AliyunMarketRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aliyun_market_record
     *
     * @mbg.generated
     */
    long countByExample(AliyunMarketRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aliyun_market_record
     *
     * @mbg.generated
     */
    int deleteByExample(AliyunMarketRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aliyun_market_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String instanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aliyun_market_record
     *
     * @mbg.generated
     */
    int insert(AliyunMarketRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aliyun_market_record
     *
     * @mbg.generated
     */
    int insertSelective(AliyunMarketRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aliyun_market_record
     *
     * @mbg.generated
     */
    List<AliyunMarketRecord> selectByExample(AliyunMarketRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aliyun_market_record
     *
     * @mbg.generated
     */
    AliyunMarketRecord selectByPrimaryKey(String instanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aliyun_market_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AliyunMarketRecord record, @Param("example") AliyunMarketRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aliyun_market_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AliyunMarketRecord record, @Param("example") AliyunMarketRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aliyun_market_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AliyunMarketRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aliyun_market_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AliyunMarketRecord record);
}