package com.fit2cloud.support.dao;

import com.fit2cloud.support.model.ExtraDataLog;
import com.fit2cloud.support.model.ExtraDataLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ExtraDataLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_data_log
     *
     * @mbg.generated
     */
    long countByExample(ExtraDataLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_data_log
     *
     * @mbg.generated
     */
    int deleteByExample(ExtraDataLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_data_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_data_log
     *
     * @mbg.generated
     */
    int insert(ExtraDataLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_data_log
     *
     * @mbg.generated
     */
    int insertSelective(ExtraDataLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_data_log
     *
     * @mbg.generated
     */
    List<ExtraDataLog> selectByExampleWithBLOBs(ExtraDataLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_data_log
     *
     * @mbg.generated
     */
    List<ExtraDataLog> selectByExample(ExtraDataLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_data_log
     *
     * @mbg.generated
     */
    ExtraDataLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_data_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ExtraDataLog record, @Param("example") ExtraDataLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_data_log
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ExtraDataLog record, @Param("example") ExtraDataLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_data_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ExtraDataLog record, @Param("example") ExtraDataLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_data_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ExtraDataLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_data_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ExtraDataLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_data_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExtraDataLog record);
}
