package com.fit2cloud.support.dao;

import com.fit2cloud.support.model.ExtraUserLog;
import com.fit2cloud.support.model.ExtraUserLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ExtraUserLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_user_log
     *
     * @mbg.generated
     */
    long countByExample(ExtraUserLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_user_log
     *
     * @mbg.generated
     */
    int deleteByExample(ExtraUserLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_user_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_user_log
     *
     * @mbg.generated
     */
    int insert(ExtraUserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_user_log
     *
     * @mbg.generated
     */
    int insertSelective(ExtraUserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_user_log
     *
     * @mbg.generated
     */
    List<ExtraUserLog> selectByExample(ExtraUserLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_user_log
     *
     * @mbg.generated
     */
    ExtraUserLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_user_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ExtraUserLog record, @Param("example") ExtraUserLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_user_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ExtraUserLog record, @Param("example") ExtraUserLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_user_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ExtraUserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table extra_user_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExtraUserLog record);
}
