package com.fit2cloud.support.dao;

import com.fit2cloud.support.model.GradeService;
import com.fit2cloud.support.model.GradeServiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GradeServiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_service
     *
     * @mbg.generated
     */
    long countByExample(GradeServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_service
     *
     * @mbg.generated
     */
    int deleteByExample(GradeServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_service
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_service
     *
     * @mbg.generated
     */
    int insert(GradeService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_service
     *
     * @mbg.generated
     */
    int insertSelective(GradeService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_service
     *
     * @mbg.generated
     */
    List<GradeService> selectByExampleWithBLOBs(GradeServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_service
     *
     * @mbg.generated
     */
    List<GradeService> selectByExample(GradeServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_service
     *
     * @mbg.generated
     */
    GradeService selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_service
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GradeService record, @Param("example") GradeServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_service
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") GradeService record, @Param("example") GradeServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_service
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GradeService record, @Param("example") GradeServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_service
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GradeService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_service
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(GradeService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade_service
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GradeService record);
}